services:
  api-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV:-dev}
    restart: always
    ports:
      - "8081:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db-dev

  api-test:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV:-test}
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8082:5000"
    depends_on:
      - db-dev

  db-dev:
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.${ENV:-dev}
    volumes:
      - db-dev-data:/var/lib/mysql
    ports:
      - "3310:3306"

  db-test:
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.${ENV:-test}
    volumes:
      - db-test-data:/var/lib/mysql
    ports:
      - "3311:3306"

volumes:
  db-dev-data:
  db-test-data:
