name: flask-mysql-test

services:
  api-test:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV:-test}
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8082:5000"
    depends_on:
      - db-test

  db-test:
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.${ENV:-test}
    volumes:
      - db-test-data:/var/lib/mysql
    ports:
      - "3311:3306"

volumes:
  db-test-data:
