services:
  api-dev:
    build:
      context: app
      dockerfile: Dockerfile.dev
    env_file:
      - .env.${ENV:-dev}
    # command: printenv
    restart: always
    ports:
      - "8081:5000"
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_USER=${MYSQL_DEV_USER}
      - MYSQL_PASSWORD=${MYSQL_DEV_PASSWORD}
      - MYSQL_DB=${MYSQL_DEV_DATABASE}
      - FLASK_DEBUG=True
    volumes:
      - ./app:/src-flask
    depends_on:
      - db-dev

  # api-test:
  #   build:
  #     context: app
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - .env.${ENV:-test}
  #   restart: always
  #   volumes:
  #     - ./app:/src-flask
  #   ports:
  #     - "8082:5000"
  #   environment:
  #     - MYSQL_HOST=localhost
  #     - MYSQL_USER=${MYSQL_TEST_USER}
  #     - MYSQL_PASSWORD=${MYSQL_TEST_PASSWORD}
  #     - MYSQL_DB=${MYSQL_TEST_DATABASE}
  #     # - FLASK_DEBUG=True
  #   depends_on:
  #     - db-dev

  db-dev:
    build:
      context: database
      dockerfile: Dockerfile.dev
    # restart: always
    env_file:
      - .env.${ENV:-dev}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEV_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEV_DATABASE}
      MYSQL_USER: ${MYSQL_DEV_USER}
      MYSQL_PASSWORD: ${MYSQL_DEV_PASSWORD}
    volumes:
      - db-dev-data:/var/lib/mysql
    ports:
      - "3308:3306"

  # db-test:
  #   build:
  #     context: .
  #     dockerfile: database/Dockerfile.dev
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
  #     MYSQL_USER: ${MYSQL_TEST_USER}
  #     MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
  #   volumes:
  #     - db-test-data:/var/lib/mysql
  #   ports:
  #     - "3307:3306"

volumes:
  db-dev-data:
#   db-test-data:
