services:
  api-dev:
    build:
      context: app
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./app:/src-flask
    ports:
      - "8081:5000"
    depends_on:
      - db-dev
        # condition: service_healthy

  # api-test:
  #   build:
  #     context: app
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   volumes:
  #     - ./app:/src-flask
  #   ports:
  #     - "8082:5000"
  #   depends_on:
  #     - db-dev

  db-dev:
    build:
      context: database
      dockerfile: Dockerfile.dev
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEV_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEV_DATABASE}
      MYSQL_USER: ${MYSQL_DEV_USER}
      MYSQL_PASSWORD: ${MYSQL_DEV_PASSWORD}
    volumes:
      - db-dev-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # db-test:
  #   build:
  #     context: .
  #     dockerfile: database/Dockerfile.dev
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
  #     MYSQL_USER: ${MYSQL_TEST_USER}
  #     MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
  #   volumes:
  #     - db-test-data:/var/lib/mysql
  #   ports:
  #     - "3307:3306"

volumes:
  db-dev-data:
#   db-test-data:
